function catchError(e: Error) {
  console.log(e);
}

export default {
  catchError,
};
